### ISSUE TITLE
Could not get the Waymo Open Dataset

### ISSUE THREAD

**Issue by Flawless1202** [lmb-freiburg/FLN-EPN-RPN#1]
I use the [link](https://console.cloud.google.com/storage/browser/waymo_open_dataset_test_fln;tab=objects?prefix=&forceOnObjectsSortingFiltering=false) and Google Drive tells me that I have no permission to access the dataset. Could you please tell me how to get the dataset?

**Comment by os1a** [comment]
Hi,

Thanks for your interest in our work.

For the Waymo processed dataset, you need to register first and accept the terms at Waymo since this data is orginally part of their dataset.

Just go to:
https://waymo.com/open/

**Comment by Flawless1202** [comment]
Hi,
Thanks for your reply. I have already registered and could access the Waymo Open Dataset now. And then how could I get your post-processed dataset?

**Comment by os1a** [comment]
Can you give me your google email address? I will give you permission to download it

**Comment by Flawless1202** [comment]
My email is a550276354@gmail.com. Thank you a lot! @os1a

**Comment by os1a** [comment]
Thanks, let me know if it works. I gave you read permission. 

I am checking now with Waymo if I can enable anyone with registration at Waymo to read it.

**Comment by Flawless1202** [comment]
Thanks for your reply, but I have not got the read permission yet. Could you please try again?

**Comment by os1a** [comment]
I am sorry for the inconvenient, It seems the dataset is somehow locked.

I have sent emails to the people from Waymo to unlock it and give read permission to people with registration at Waymo. I will update you as sonn as I get a reply.

**Comment by os1a** [comment]
Hi @Flawless1202,

Are you still no able to download it?

Can you check once more under the link 
https://console.cloud.google.com/storage/browser/waymo_open_dataset_test_fln;tab=objects?prefix=&forceOnObjectsSortingFiltering=false

and go to the permission (rightmost button) to see that your email address is given a read permission?

**Comment by Flawless1202** [comment]
hi @os1a ,
I have already got the read permission, thanks a lot!

**Comment by WinstonDeng** [comment]
@os1a 
Hi, the same issue I met is that no permission occurs when I download Waymo Open Dataset via your link. 
Could you give me permission?
My email is winstondeng517@gmail.com

**Comment by os1a** [comment]
Hi @WinstonDeng,

I added you to the permission list, please allow for few hours before you try again to download.
