### ISSUE TITLE
Can your model predict the trajectory accurately even when the camera itself moves

### ISSUE THREAD

**Issue by Senwang98** [lmb-freiburg/FLN-EPN-RPN#3]
Hi, @os1a 
In an autonomous driving environment, if there is relative motion between the camera itself and the detected object, does your model still achieve good prediction performance?

**Comment by os1a** [comment]
Hi, @1187697147 

I think what you refer to is the ego-motion of the camera. This is something we take into account in our setup especially the RTN which is responsible of converting the predicted RPN hypotheses into the future using the future ego-motion.

Hope this answers your question.

**Comment by Senwang98** [comment]
Yes, there is no problem with your understanding. So your work is really meaningful!
